//SPDX-License-Identifier: MIT
pragma solidity ^0.7.0;

import "@openzeppelin/contracts-upgradeable/access/AccessControlUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/utils/ContextUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/token/ERC721/ERC721Upgradeable.sol";
import "@openzeppelin/contracts-upgradeable/token/ERC721/ERC721PausableUpgradeable.sol";
import "@openzeppelin/contracts-upgradeable/proxy/Initializable.sol";
import "@openzeppelin/contracts/utils/Strings.sol";
import "./ICryptoMoth.sol";

contract CryptoMoth is
    Initializable,
    ContextUpgradeable,
    AccessControlUpgradeable,
    ERC721PausableUpgradeable,
    ICryptoMoth
{
    using Strings for uint256;

    bytes32 public constant MINTER_ROLE = keccak256("MINTER_ROLE");
    bytes32 public constant BURNER_ROLE = keccak256("BURNER_ROLE");
    bytes32 public constant PAUSER_ROLE = keccak256("PAUSER_ROLE");
    mapping(uint => uint) public tokenIdToBlockId;
    mapping(uint => uint) public blockIdToTokenId;
    mapping(uint => bool) public isBlockMinted;

    function initialize(
        string memory name,
        string memory symbol,
        string memory baseURI
    ) public virtual initializer {
        __ERC721PresetMinterPauserAutoId_init(name, symbol, baseURI);
    }

    /**
     * @dev Grants `DEFAULT_ADMIN_ROLE`, `MINTER_ROLE` and `PAUSER_ROLE` to the
     * account that deploys the contract.
     *
     * Token URIs will be autogenerated based on `baseURI` and their token IDs.
     * See {ERC721-tokenURI}.
     */
    function __ERC721PresetMinterPauserAutoId_init(
        string memory name,
        string memory symbol,
        string memory baseURI
    ) internal initializer {
        __Context_init_unchained();
        __AccessControl_init_unchained();
        __ERC165_init_unchained();
        __ERC721_init_unchained(name, symbol);
        __Pausable_init_unchained();
        __ERC721Pausable_init_unchained();
        __ERC721PresetMinterPauserAutoId_init_unchained(baseURI);
    }

    function __ERC721PresetMinterPauserAutoId_init_unchained(
        string memory baseURI
    ) internal initializer {
        _setupRole(DEFAULT_ADMIN_ROLE, _msgSender());

        _setupRole(MINTER_ROLE, _msgSender());
        _setupRole(PAUSER_ROLE, _msgSender());

        _setBaseURI(baseURI);
    }

    function pause() public virtual {
        require(
            hasRole(PAUSER_ROLE, _msgSender()),
            "CryptoMoth: must have pauser role to pause"
        );
        _pause();
    }

    function unpause() public virtual {
        require(
            hasRole(PAUSER_ROLE, _msgSender()),
            "CryptoMoth: must have pauser role to unpause"
        );
        _unpause();
    }

    function isMinted(uint blockId) external view override returns (bool) {
        return isBlockMinted[blockId];
    }

    function dnaForBlockNumber(uint256 _blockNumber) external pure override returns (uint) {
        return uint(keccak256(abi.encodePacked(_blockNumber.toString())));
    }

    /**
     * @dev main mint functionality. Permitted for Minters
     */
    function mint(uint blockId, address to) public override {
        require(
            hasRole(MINTER_ROLE, _msgSender()),
            "CryptoMoth: must have minter role to mint"
        );
        require(isBlockMinted[blockId] == false, "CryptoMoth: blockId already minted");

        uint tokenId = totalSupply();
        blockIdToTokenId[blockId] = tokenId;
        tokenIdToBlockId[tokenId] = blockId;
        isBlockMinted[blockId] = true;

        _safeMint(to, tokenId);
    }

    function setBaseURI(string memory baseURI_) external {
        require(
            hasRole(DEFAULT_ADMIN_ROLE, _msgSender()),
            "CryptoMoth: must have admin role"
        );
        super._setBaseURI(baseURI_);
    }

    function tokenURI(uint tokenId) public view virtual override returns (string memory) {
        require(_exists(tokenId), "CryptoMoth: URI query for nonexistent token");

        string memory baseURI = baseURI();
        return bytes(baseURI).length > 0 ? string(abi.encodePacked(baseURI, tokenIdToBlockId[tokenId].toString())) : "";
    }

    function burn(uint tokenId) public virtual {
        require(_isApprovedOrOwner(_msgSender(), tokenId) || hasRole(BURNER_ROLE, _msgSender()), "caller is not owner nor approved");
        _burn(tokenId);
    }

    function blockOfToken(uint tokenId) external view override returns (uint) {
        require(_exists(tokenId), "CryptoMoth: blockOfToken query for nonexistent token");
        return tokenIdToBlockId[tokenId];
    }

    uint[49] private __gap;
}
