//SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "./Trait.sol";

contract Pants is Trait {
  // Skin view
  // Short pants
  string public constant SHORT_FANCY =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEVhYmzOfBTTexbcghM7VPhxAAAAAXRSTlMAQObYZgAAAFhJREFUOMtjYBgFVAdhU0MzUQT2rdxXhyKwbt/e9SgCdfv27kYTqEUVqNy1M2s0aIcNCN0eNgtF4OWqXXtRBN7m7duJIvCzbi+qip95tT9RBHbmZb6lrzcA0kkexhJMXJEAAAAASUVORK5CYII=";
  string public constant SHORT_BLACK =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEVlLWcXGBYcHRsfIR/lS+CTAAAAAXRSTlMAQObYZgAAAE9JREFUOMtjYBgFVAehQIAiUBtaW4siEFtbG4+qora2HE0gFlWgNBbN0FEwpNNIGlp0Xg0tRU0jd2NrS1EEvtaipaKvsbVfUQ2NjaVzGgEA9JIWUHO78tYAAAAASUVORK5CYII=";
  string public constant SHORT_BLUE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEVyZXMUMGQeOXQfSIxwGWR2AAAAAXRSTlMAQObYZgAAAFhJREFUOMtjYBgFVAdhU0MzUQT2rdxXhyKwbt/e9SgCdfv27kYTqEUVyFy3Mm80aIcNCF0WNgtF4OWqXXtRBN7m7duJIvCzbi+qip95tT9RBFZm5b6krzcAVPMeeUDvN08AAAAASUVORK5CYII=";

  // Long pants
  string public constant LONG_FANCY =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAD1BMVEVzLWnOfBTTexbbgRLfhBdEB3xUAAAAAXRSTlMAQObYZgAAAJFJREFUSMftlMERAyEMA68FMA3YogELGjju+q8pFBD7mzzYh187GjOArutw+DNK1VL2CAXQFBSGghGE2xMKsjq7A7FALEmFuxN3Y7IkVPyNE/qANpcZCtU2+6jnRRwOX3qiQHZNWChQzWDwWPC6sBD/sKGycCcJQyvFZ9JV2th85gnNn1yAI26aUXT3nfEHV/ABZ+MVbV8H+hoAAAAASUVORK5CYII=";
  string public constant LONG_BLACK =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAD1BMVEVzLWkVFhQYGRccHRsgIR/TWU0JAAAAAXRSTlMAQObYZgAAAIhJREFUSMftlLENBDEIBN0CfhqApxEQ/df064sPLrwP2MCJRyss27PWZPJnoS1EWErAQsWCowQ0LMw1S4AvwKwFuAX8NDQzYFvYs26wPADXQ25FcNR5EZPJjSfo+4EmtARCVE3Na8D3EUH9w1L4eMIbYMMT2bgKDQAeG3oAM9SmSRKcQuOFK/gBESgYVnnv5RIAAAAASUVORK5CYII=";
  string public constant LONG_BLUE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAD1BMVEUAAAAUMGQfOXQeRocfTaK1PriXAAAAAXRSTlMAQObYZgAAAJFJREFUSMftlMERAyEMA68FMA3YogELGjju+q8pFBD7mzzYh187GjOArutw+DNK1VL2CAXQFBSGghGE2xMKsjq7A7FALEmFuxN3Y7IkVPyNE/qANpcZCtU2+6jnRRwOX3qiWN01YaFANYPBY8HrwkL8w4bKwp0kDK0Un0lXaWPzmSc0f3IBjrhpRtHdd8YfXMEHZOIVaw91yZoAAAAASUVORK5CYII=";

  // New pants
  string public constant ASTRONAUT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAG1BMVEVPsue5AABWV1VvcW5/gX6+wb3Lzsrm6OXy9PHHtKnUAAAAAXRSTlMAQObYZgAAAMtJREFUSMftlLENAyEMRW8FmgwAGwAbcCscpE2BYAG8QTx37CsT2ZZS8yl58v2TxTuOnZ2vxGAAwQJ8tABtQu21X1ftIjDfDQdOEIGBAyZOlAGY91E6DBiodHDu4Wp3TgTaqn1CW1oH/gtUO9Te5A655FJKKiJAd/kkSl619yElc+E7O394IloaCN6aoAHsCD6yJ2CuJ70xGcBbBKiJBFkEyif4jSodyBEv5xRPsGXaUjzBBQeYnqjyhJzZFDnJnjjpVvMEOYJM8bvwD2e5RJo7hlZhAAAAAElFTkSuQmCC";
  string public constant COWBOY =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAIVBMVEUAAAAkFwYTH04WIFYyIwsUJWM4JwpZKgdvNxGJQBL+1QCN1Ay8AAAAAXRSTlMAQObYZgAAANBJREFUSMftlEEKwjAQRXuFQugBRN1LGPeBafY25ASN9gZt9QJNbpA5gdc0boWZgiC46N/m8SdhyKuqLVs+Mk0rwDj8FPCnvtMlLODqFsCD44HGeucBWMCocEXEmm9Qt+CdMEIbDPIdgkGngX8FnRUSUWKBSClRzJEHYs6xhAWe8/t4mYVVj8M0rS58y5Y/9AQc9n0n/DAHu4sF7aSGYEFowPporEXFN+jGIHjBE74pIzSvInDKlDvwQCZlW8kTKc9ExQWCJ+6yJ2Kc4/L4whMvV8tLH1+dY+AAAAAASUVORK5CYII=";
  string public constant LUMBERJACK =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAFVBMVEUAAABiMQ8IRWARSWUAVHpgQShiZGEoVAkJAAAAAXRSTlMAQObYZgAAALFJREFUSMftlLENQyEMRP8KFGQAzhPYTABZgOIPkP2XiN1G8qEoTQqOkifOgO6u6+joQ6VsgLp+BaiFDXs2nSMF2sDsCk0BsQ5xKLfQblDJT8CAgllgwsAsZMSIkt8ijhcFu6bAGFBXXaWQx/b9et+rkn94vErZfvjR0f/1BJpEiI1kVFQaSbkMmd42PKORcwa4Aasiz3hXbjF9DttUkfQcMG+KRmaIjoiVAtERsb7uiTct3iR+3MrH0QAAAABJRU5ErkJggg==";
  string public constant SUIT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAFVBMVEUAAAAKFh8OHiwwHAs4IgYZKDZOMROMMu4EAAAAAXRSTlMAQObYZgAAAJdJREFUSMftlMEJgDAMRV2hhQ6QQDZwA4v3BNxA3H8Ek6vQHwS99ZecfPyk2PxlmZp6qK8JsPVfHQpVYq5lCPhHEz54CIjFYUMACyOAooWkgGLAGpxBvQgA4QABwS2u69yjxj+qb2vUfPRTr/VzDKQOzMWFcsKaBwlcoOYLdBBwSFYwWkQQJEBVNEM4aDJk4pABcQv9PiduMCsrUNLT6DgAAAAASUVORK5CYII=";
  string public constant KNIGHT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAHlBMVEUAAAA2NjZKSkpxcXGZmZmzs7PAwMDNzc3a2trn5+difNTDAAAAAXRSTlMAQObYZgAAAMBJREFUSMftlDEOwjAMRXuFemJ1WJgJ4gJYFRdoEBdI071q6AhDRC6Q9LhQRpDNiJDy56cnWUpeVZWVvQ3wt8A0WW9dcCLgXEwCYBZg5oFhAa4bFiDStCMi/oK+PQEgfwdO5oIIwBtGY2WDN142+KYTDVprpfV2zQJ1DagUYnn0ZX/XiWBTTFboRAhjzLmfJcDnHCVgPxzvtxXfiYMmkjqB2J6T+InBxCxmAI3tvhm8bGg6LxlemZA6oRTgsxUfhgc/NTk1w29ieQAAAABJRU5ErkJggg==";
  string public constant POLICE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAElBMVEUAAAAGHDMLJkIIKUozJwZKOQilffLwAAAAAXRSTlMAQObYZgAAALxJREFUSMftlNENBCEIRK8FoAKgAoYW3A7W/ls59ncT+L1cIv6ZcVDivM/n1KlXrfVbQabDydAKAAe7WSsQTWcVbwVWp0UlWwGrBZR7B3bAwmi4Awenae8Qglq9IJ2qB/dzCIp6KNEw5n3vfd2tYO/7Wuu+zqc/9XecoMJAsaLHAFTgOkVQORHAkFE2towBA2Ll0rcQE68QDykvTmmiF3hxQt1igJmAyqSfQxataKBdMWKvNXDiYcTDivf+F1qGI59+bsDhAAAAAElFTkSuQmCC";

  // Front view
  // Short pants
  string public constant FRONT_SHORT_FANCY =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAADFBMVEUAAADTexbOfBTcghMsdKvZAAAAAXRSTlMAQObYZgAAAB5JREFUCNdjYKAHyKoGEmGhQKJ2LojYC2OVziWgEwALYAYRFZBR2QAAAABJRU5ErkJggg==";
  string public constant FRONT_SHORT_BLACK =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAADFBMVEUAAAAXGBYcHRsfIR8riSZSAAAAAXRSTlMAQObYZgAAAB1JREFUCNdjYKAHCE0DEaFAojYWRNTCWLGxBHQCANcVBM4rWVNSAAAAAElFTkSuQmCC";
  string public constant FRONT_SHORT_BLUE =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAADFBMVEUAAAAeOXQUMGQfSIyVuGQPAAAAAXRSTlMAQObYZgAAAB5JREFUCNdjYKAHyIoEEmGhQKJ2LojYC2PFTiWgEwD/pwXPMca/4wAAAABJRU5ErkJggg==";

  // Long pants
  string public constant FRONT_LONG_FANCY =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgBAMAAADpp+X/AAAAD1BMVEUAAADTexbOfBTbgRLfhBffcoAOAAAAAXRSTlMAQObYZgAAADZJREFUGNNjYBiSQEhJWBnMEBQSFAQzhA0VHcEMEUNlCEPYUdEQKqICYQgLKaIxBAWFDPFaBAAzRwSS/7mIvgAAAABJRU5ErkJggg==";
  string public constant FRONT_LONG_BLACK =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgBAMAAADpp+X/AAAAD1BMVEUAAAAYGRcVFhQcHRsgIR/IZ4SkAAAAAXRSTlMAQObYZgAAACxJREFUGNNjYBiSQEhJWBnMEBQSFAQzRBwVHaEMFUdcIkKKaAxBQSFHvBYBAFFsBRcWOvIhAAAAAElFTkSuQmCC";
  string public constant FRONT_LONG_BLUE =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgBAMAAADpp+X/AAAAD1BMVEUAAAAfOXQUMGQeRocfTaJii7rMAAAAAXRSTlMAQObYZgAAADZJREFUGNNjYBiSQEhJUBHMEBQSFAQzhA0VHcEMEUNlCEPYUdEQKqICYQgLKaIxBAWFDPFaBAAxrQSOcxLd+gAAAABJRU5ErkJggg==";

  string public constant FRONT_ASTRONAUT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgBAMAAADpp+X/AAAAG1BMVEUAAAC+wb3Lzsrm6OXy9PG5AABvcW5/gX5WV1XM19zcAAAAAXRSTlMAQObYZgAAAD9JREFUGNNjYBiSQEhRSBHMEHZSMQQzlI2UjcAMFSNlJ1SRoNBQVVRdKk4qaGrSy9LLwAwgnQ5mdLRldDAwAADYYguPdveXlwAAAABJRU5ErkJggg==";
  string public constant FRONT_COWBOY =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgBAMAAADpp+X/AAAAHlBMVEUAAAA4JwoWIFYUJWMTH04yIwskFwZvNxGJQBJZKgd8QHc+AAAAAXRSTlMAQObYZgAAAE9JREFUGNNjYBiSQMjE2RXMCFZ2MQMzAo2dRcEMUWHHMDBDUDQRwggVTYRIhYWmQkRSQ1MDwYyKiukdYEZ7+4x2MKO8fHo5mDFRcqIkAwMArrcPebGzeOMAAAAASUVORK5CYII=";
  string public constant FRONT_LUMBERJACK =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgBAMAAADpp+X/AAAAFVBMVEUAAAARSWUAVHoIRWBiMQ9gQShiZGHXzFGbAAAAAXRSTlMAQObYZgAAAEZJREFUGNNjYBiSQFDJSBDMMFQ0EgYzhAyNFCEMQUOIiKGwoTGEIQhTI2yoCJOCiBgZGiuDGa4hriFgBpB2BTPcUtxSGBgAeOIIql2Q1FEAAAAASUVORK5CYII=";
  string public constant FRONT_SUIT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgBAMAAADpp+X/AAAAFVBMVEUAAAAKFh8OHiwZKDZOMRM4IgYwHAtTPbD1AAAAAXRSTlMAQObYZgAAADVJREFUGNNjYBiSQEhRUBDCMBJWBDOUjYSNIAwlISNUKUyGsqGwEQ7triGuIWBGWGpYKgMDAElYB6ymxDOdAAAAAElFTkSuQmCC";
  string public constant FRONT_KNIGHT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgCAAAAAA+4qcQAAAAAnRSTlMAAHaTzTgAAAB2SURBVCjP7c2xDcJQEIPhj0CFdAPkLUAGYGQWQPQRAzBAMgBXQfUk6BBNEhiAEjcn2f/Z/PVrreAslLFEi2ZOcroNVFDTN3HgAhvodRy7T+mJkuzbmRARolheqHXemYxQlVhWUpUyF2IYRuzAGl5Pt8f2Pl7xBva4HQsbSM+kAAAAAElFTkSuQmCC";
  string public constant FRONT_POLICE =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgBAMAAADpp+X/AAAAElBMVEUAAAALJkIIKUoGHDNKOQgzJwa3pY29AAAAAXRSTlMAQObYZgAAAENJREFUGNPVy1ENACAIRVEqgAmABGAFaED/LG6gIXxfZ3u7AF+OmPjCB0ImDUTDgfqA2alheuGv2g+6bK7IikZWFsABUEcHhkozIfgAAAAASUVORK5CYII=";

  constructor() {
    _tiers = [
      5000,
      5700,
      6400,
      7000,
      7600,
      8200,
      8800,
      9300,
      9500,
      9700,
      9900,
      9950,
      10000
    ];
  }

  function getName(uint256 traitIndex)
    public
    pure
    override
    returns (string memory name)
  {
    if (traitIndex == 0) {
      return "";
    } else if (traitIndex == 1) {
      return "Short Black";
    } else if (traitIndex == 2) {
      return "Long Black";
    } else if (traitIndex == 3) {
      return "Short Blue";
    } else if (traitIndex == 4) {
      return "Long Blue";
    } else if (traitIndex == 5) {
      return "Police";
    } else if (traitIndex == 6) {
      return "Suit";
    } else if (traitIndex == 7) {
      return "Lumberjack";
    } else if (traitIndex == 8) {
      return "Knight";
    } else if (traitIndex == 9) {
      return "Short Fancy";
    } else if (traitIndex == 10) {
      return "Long Fancy";
    } else if (traitIndex == 11) {
      return "Astronaut";
    } else if (traitIndex == 12) {
      return "Cowboy";
    }
  }

  function _getLayer(
    uint256 traitIndex,
    uint256,
    string memory prefix
  ) internal view override returns (string memory layer) {
    if (traitIndex == 0) {
      return "";
    } else if (traitIndex == 1) {
      return _layer(prefix, "SHORT_BLACK");
    } else if (traitIndex == 2) {
      return _layer(prefix, "LONG_BLACK");
    } else if (traitIndex == 3) {
      return _layer(prefix, "SHORT_BLUE");
    } else if (traitIndex == 4) {
      return _layer(prefix, "LONG_BLUE");
    } else if (traitIndex == 5) {
      return _layer(prefix, "POLICE");
    } else if (traitIndex == 6) {
      return _layer(prefix, "SUIT");
    } else if (traitIndex == 7) {
      return _layer(prefix, "LUMBERJACK");
    } else if (traitIndex == 8) {
      return _layer(prefix, "KNIGHT");
    } else if (traitIndex == 9) {
      return _layer(prefix, "SHORT_FANCY");
    } else if (traitIndex == 10) {
      return _layer(prefix, "LONG_FANCY");
    } else if (traitIndex == 11) {
      return _layer(prefix, "ASTRONAUT");
    } else if (traitIndex == 12) {
      return _layer(prefix, "COWBOY");
    }
  }
}

