// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhyssyhNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMmdy+/:`   ` `+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo::::/dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMmho/-`` -/ydmmh  +MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm/.   `sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMds/.`  `+dNMMMMMo  :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm+-   .hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMmo/.  .:+mMMMMMMN+  -/MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmNMMMMMMMMMMMMMMMMd+-   .dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMh/-   -+dMMMMMMNh-  `+yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMm/`..oMMMMMMMMMMMMMMm+.   -mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMM:.   .omMMMMMNy-   ./oMMMMMNmmNMMMMMmmmmMMMMMMMMNNMMMMMMMMNmNMs+   .hhhhddmNMMMMMm+.   -mMNNMMMMMMMMNNmNMMMMMMNNmNMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMy`   -+mMMMMMNo.  :/yMMMN/:-..+Mmho++///oMMMMNs-..-/yNmo:--:sMy/`        `.-yMMMN-.   `o/:--+NMMMd/:-..hMMMm/:-..yMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMmo-`  .-/oyhdmdhyhNMMMN:`   .s/. ``   `:MMMm/    `. --` `/+MMMm:  +yyo     +MMN:     `-+s+  sMMd/    sMMMm-    oMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMmhys+/:--.`.:yNMMMM/:    ` `-+.    .mMMd+`   -hms    //NMMMd  `NMN:.   .NMM+     :hdo-  .hMm+`   oMMMNo`   +MMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMNhsoymmNMMMMMN-  `+MMMo/`    .odMo    `dMMm+`   :NMN-   ./NMMMN-  sMMo/   `dMMs    `os:`  .omMNo.   /MMMMs:   :MMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMNy+``   :dMMMMMy-  ..NMy--   -hNMMy   `-yMMmo`   :NMM/    .NMMMM+  :MMh+`  `hMMd`    ``  `-yNMMM+:   :NMMMy+   .NMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMmo-    -/NMMMMmo/`   :Mm./   -NMMMm-   +oMMMo.   -NMMs    `dMMMN+  -NMm+.   sMMN.       -odMMMMMo-   .NMMMd-`  `dMMNdmMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMNo.   `/yMMMMNs/:    /NM/:`  `mMMMMo-  -+MMN+-   `mMMd`  .odMMMm:  :NMM//   :MMN+    ``  dMMMMNd/     dMNy:     oMms- yMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMs:    +hMMMNo/:`   -hMMd -   oMMMMh:`` :sy/`     oNy:   .NMhmMM+ `sMMMh.    hd+`    -s/  +MMmo-      -h/` `    .s: `:yNMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMN:    `hMMd+/:`   :hMMMM+    `NMMMMmNMMmho-`-     ```/   hMm  +NMhNMMMMo.      .-    oNm`  :- `/h.      .oy`      -sNMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMm     yNyo::`  -smMMMMMMm/-..+MMMMMMMd/+yNMMMy+-.-+hNMhmNMN:   .hddmmNMMMMNdysdMm+-.:hMMm/--/yNMMMhs++sdms.    .omMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMM.    . .` `:smMMMMmhssoshNMMMMMMMMMMMm.  +NMMMmNMMNdhhyo+:   `..------:/++oydNMMMMMMMMMMMMMMMMMMMMMMmo.      :MMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMNo:..-:+sdNMMMdy:`   `--``yMMMMMMd.`hMm`  .oo+` .`````                        /MMMs:../oMMMMMMMMMMN/ .+y`   .NMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMdy+-` `:smNMMo `NMMMMy`  .MM- -/oo.--.                        `./ohNMN+.  /sNMMMMMMMMMM- -Nh.   `dMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMho/.  `omMMMMMh` .mMMMs    +Mh`:yNMMNNMNNh-  `:o++:-.`    -/+shmNNMMMMN+:  -yMMMMMMMMMMMM/  `  `./dMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMo/.  -+mMMMMMN+  .+MMMs.   :NNshNMMMMMMMMMMNsyNMMNNNNNN.  +NMMMMMMMMMMN+:  `yMMMMMMMMMMMMMNy/:/oyhNMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMh`   /yMMMMMmo.  -+dMMy-`  :NMMNmmNMMMMMMMMMMMMMMMMNMMMd`:hMmddmNMMMMMN/:  `yMMMMMMMMMMMMMMMMMNNmmdMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMN-   -hNMMMMh:` -omMMd:-  -mds:.``.hMMMNo-.-/yNh+::-yMMhmMmo.`./++dMMN//   /+:-.-:/+ooooooo+++//:omMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMNh/-.`.-/osyhhdmNMMm-/  `+-`    `.hMMd-   `-... `/+MMMmy/sdd-   -hMM+/   `:os:  -`   ```.--```-yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMNNNmmdhyso:`./mMMN:/    `:s+  `:oMMd` ` .hNy   //NMMM- .NMy    +MMs:`  /yy:` .sNmddddmmmh:  :mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMNy+..:+yMMMMMo` .+MM+/`  -smMh`  +/MMm` `:.mMm.  `/NMMMo  yMd`   /NMh.`  -/.  -sNMMMMMMMMNy: .yNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMmo-`   /mMMMNs-` `oMy:-  oNMMm.  ::NMN-  /.mMN-   .mMMMs  +MN-   -NMN.      .+hNMMMMMMMMMd+-`/mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMN+-   `oNMMNh/:`  :mN-/  :MMMM/   :dMm/  :.hMN+    dMMN+  +MM+   `dMN/   `  -NMMMNh/MMMMNs/..yMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMM+:   `yMMNh+:.  .sNM+-   dMMMd    /h/`   `/ms-    :Nds. -yMMm    :do.   .+/ `mNms-./MMMh::`+NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMN.   `hMms/-. `:yNMMM..  /MMMMo     `:/`   `.:/    `.`.:yNMMMs ``  .::   /Nd. .-.-omMMm/ `-hMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMm    +y/`` `-odMMMMMMms++mMMMMNhs++ymMMdyooymMNyo++oyhNMMMMMMNyyysymMNs++yMMmsosdMMMMy.  .syyyhdmmNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMo``  ``./sdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs` ``````````..-/+shNMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMNhhhdmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyymmdddmmmmmmmmmmmmNMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
// MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
