//SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "./Trait.sol";

contract Eyes is Trait {
  // Skin view
  // Mouse: 0
  string public constant MOUSE_RIGHT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEVlLWckJCScnJzx8fGYJxp/AAAAAXRSTlMAQObYZgAAABpJREFUOMtjYBhCgIsLTYCXl2EUjIJRMGAAAKbZAC/5M7/QAAAAAElFTkSuQmCC";
  string public constant MOUSE_LEFT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEVlLWckJCScnJzx8fGYJxp/AAAAAXRSTlMAQObYZgAAABpJREFUOMtjYBhCgIsLTYCdnWEUjIJRMGAAAHzHACMa7IPxAAAAAElFTkSuQmCC";
  string public constant MOUSE_CROSSED =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEVlLWckJCScnJzx8fGYJxp/AAAAAXRSTlMAQObYZgAAABpJREFUOMtjYBhCgIsLTYCdl2EUjIJRMGAAAJHNACkBjKxHAAAAAElFTkSuQmCC";
  string public constant MOUSE_3D =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEUAAAD8RkZGw/zx8fFFHVXFAAAAAXRSTlMAQObYZgAAACJJREFUOMtjYBi8wP7/ART+/19f/6Op4D/AMApGwSgYKAAA+5EG+o56Gh4AAAAASUVORK5CYII=";
  string public constant MOUSE_LASER =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEUAAE/5Pz/+hoZe3CQjAAAAAXRSTlMAQObYZgAAABtJREFUOMtjYBhCgIMDTUBNjZCKUTAKRgHtAAB+8QBtvTcAMwAAAABJRU5ErkJggg==";
  string public constant MOUSE_SUN =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAQMAAACQp+OdAAAABlBMVEUAAAAkJCRXyFKEAAAAAXRSTlMAQObYZgAAABdJREFUKM9jYKAZ4P//AcoyZhgFwxQAACR0AjJvfSwqAAAAAElFTkSuQmCC";

  // Frog: 1
  string public constant FROG_RIGHT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEVlLWcAAABCpkz///+XoPGRAAAAAXRSTlMAQObYZgAAABpJREFUOMtjYBg0YAEXmsAFXoZRMApGwSAGAJ86AYhDlf2iAAAAAElFTkSuQmCC";
  string public constant FROG_LEFT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEUAAAAAAABCpkz///9ZYjdQAAAAAXRSTlMAQObYZgAAABpJREFUOMtjYBg0YAEXmkABO8MoGAWjYBADACvZASKoINImAAAAAElFTkSuQmCC";
  string public constant FROG_CROSSED =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEVhYmwAAABCpkz///8p9twwAAAAAXRSTlMAQObYZgAAABpJREFUOMtjYBg0YAEXmkABL8MoGAWjYBADAEGrASg0BSMWAAAAAElFTkSuQmCC";
  string public constant FROG_CLOSED =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEUAAAQujUVCpkxbHzrDAAAAAXRSTlMAQObYZgAAABpJREFUOMtjYBg0YAEXmkAAK8MoGAWjYBADALAEAQBNGbSAAAAAAElFTkSuQmCC";
  string public constant FROG_LASER =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEVHAOPfNB7fbmA8zv7oAAAAAXRSTlMAQObYZgAAABtJREFUOMtjYBg0QIEDTWCGGiEVo2AUjIKBBADbLwEPsGTK8wAAAABJRU5ErkJggg==";
  string public constant FROG_SUN =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAQMAAACQp+OdAAAABlBMVEVrdEccEwC5FntbAAAAAXRSTlMAQObYZgAAABdJREFUKM9jYKA24P//Acp6zjAKhjsAAIyMAubQmKY3AAAAAElFTkSuQmCC";

  // Cats: 2
  string public constant CAT_RIGHT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEV0ADMICAjW4cj17uQ4AAAAAXRSTlMAQObYZgAAABZJREFUOMtjYBjeQEWFYRSMglFAIwAA9xwASXm4vVAAAAAASUVORK5CYII=";
  string public constant CAT_LEFT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEUAAAIICAjW4chWtdgHAAAAAXRSTlMAQObYZgAAABZJREFUOMtjYBjeQEKCYRSMglFAIwAApigAMYl5xA8AAAAASUVORK5CYII=";
  string public constant CAT_CROSSED =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEUAAOQICAjW4cg2xUsqAAAAAXRSTlMAQObYZgAAABZJREFUOMtjYBjeQEWCYRSMglFAIwAAzqgAPQRpQ1IAAAAASUVORK5CYII=";
  string public constant CAT_CLOSED =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAQMAAACQp+OdAAAABlBMVEVzADHzkhJnCg09AAAAAXRSTlMAQObYZgAAABJJREFUKM9jYBgQkMYwCoYFAAC4VgBnaf6kIQAAAABJRU5ErkJggg==";
  string public constant CAT_3D =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEVlLWfiYGBgt+L///9ibcCbAAAAAXRSTlMAQObYZgAAAB5JREFUOMtjYBhW4P9/NP7r62gif+wZRsEoGAXUAQCX2Ab61dcG7QAAAABJRU5ErkJggg==";
  string public constant CAT_LASER =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEVHAMzzUjr4koPwf4VCAAAAAXRSTlMAQObYZgAAABtJREFUOMtjYBhWQIEDTWCGGiEVo2AUjAJyAQCTdwEPtoqJgAAAAABJRU5ErkJggg==";
  string public constant CAT_SUN =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAQMAAACQp+OdAAAABlBMVEUAAAAICAhtdupNAAAAAXRSTlMAQObYZgAAABdJREFUKM9jYKAj4P//AcpKYxgFwwIAAFgNAmXWxHedAAAAAElFTkSuQmCC";

  // Ape: 3
  string public constant APE_RIGHT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEV7+wMAAACSayD///8/JDF/AAAAAXRSTlMAQObYZgAAABpJREFUOMtjYBhCQGMBmoDJBYZRMApGwYABAF4KAc2JOLBoAAAAAElFTkSuQmCC";
  string public constant APE_LEFT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEVlLWcAAACSayD////l64lvAAAAAXRSTlMAQObYZgAAABpJREFUOMtjYBhCQGMBmoBMAcMoGAWjYMAAALlcAVV93WgeAAAAAElFTkSuQmCC";
  string public constant APE_CROSSED =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEVhYmwAAACSayD///9bvaTOAAAAAXRSTlMAQObYZgAAABpJREFUOMtjYBhCQGMBmoDMBYZRMApGwYABAAnaAbU/MvXGAAAAAElFTkSuQmCC";
  string public constant APE_CLOSED =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEUAAEqCXhuSayBzqykqAAAAAXRSTlMAQObYZgAAABpJREFUOMtjYBhCQGMBmoBIAMMoGAWjYMAAAC0sAS1SowumAAAAAElFTkSuQmCC";
  string public constant APE_3D =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEVlLWffNB5PoNv//PdcxyH/AAAAAXRSTlMAQObYZgAAAB5JREFUOMtjYBg64D8QoIpcX4Ou5A/DKBgFo4BeAABeJQd7/5unYgAAAABJRU5ErkJggg==";
  string public constant APE_LASER =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEVwAMPfNB/fb2FvgwzdAAAAAXRSTlMAQObYZgAAABtJREFUOMtjYBhCQEEBTWDGDEIqRsEoGAW0AwDvEwGxXm8ZoQAAAABJRU5ErkJggg==";
  string public constant APE_SUN =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAQMAAACQp+OdAAAABlBMVEVqZWMoHACkYH8mAAAAAXRSTlMAQObYZgAAABdJREFUKM9jYKAZ4P//AcrKYRgFwxQAAI43AmtGeoLrAAAAAElFTkSuQmCC";

  // Alien: 4
  string public constant ALIEN_RIGHT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEUAAOoJDAdnzujtq9nGAAAAAXRSTlMAQObYZgAAABpJREFUOMtjYBjKQEUFTUBCgmEUjIJRQC8AAKXTAHkKAFKsAAAAAElFTkSuQmCC";
  string public constant ALIEN_LEFT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEUAAKoICAhsyOJ1xWj1AAAAAXRSTlMAQObYZgAAABpJREFUOMtjYBjKQEICTUBFhWEUjIJRQC8AAKQ7AHlAkZAkAAAAAElFTkSuQmCC";
  string public constant ALIEN_CROSSED =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEVwANQICAhsyOI5MQBWAAAAAXRSTlMAQObYZgAAABpJREFUOMtjYBjKQEIFTUBFgmEUjIJRQC8AAKUHAHlRv0sRAAAAAElFTkSuQmCC";
  string public constant ALIEN_CLOSED =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEVHAM5BuNpWwN7KSNqmAAAAAXRSTlMAQObYZgAAABpJREFUOMtjYBjKQEMDTUBEhGEUjIJRQC8AAKZbAHm+C5+oAAAAAElFTkSuQmCC";
  string public constant ALIEN_3D =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEVlLWfiR0xHx+L8/v9h5aJlAAAAAXRSTlMAQObYZgAAAB5JREFUOMtjYBhC4P9/NP7112gif+wZRsEoGAX0AgCE5Qb6uWgeRgAAAABJRU5ErkJggg==";
  string public constant ALIEN_LASER =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEUAAFzeVmXmgYyfcOAVAAAAAXRSTlMAQObYZgAAACJJREFUOMtjYBhCgIMDTUBNDU1gxgw0AQUFhlEwCkYBjQAANawBzdOo8sAAAAAASUVORK5CYII=";
  string public constant ALIEN_SUN =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAQMAAACQp+OdAAAABlBMVEVya3UICAiZn1B1AAAAAXRSTlMAQObYZgAAABdJREFUKM9jYKA94P//AcpKYxgFwwsAAG2RAmVHLjXYAAAAAElFTkSuQmCC";

  // Doge: 5
  string public constant DOGE_RIGHT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEUAANUVEQ7///+UYrkZAAAAAXRSTlMAQObYZgAAABZJREFUOMtjYBjEQIUAfxSMglEwoAAAB+cASbvRsD4AAAAASUVORK5CYII=";
  string public constant DOGE_LEFT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEUAAH0VEQ7////gJiQQAAAAAXRSTlMAQObYZgAAABZJREFUOMtjYBjEQIIAfxSMglEwoAAAsVAAMYYGv/kAAAAASUVORK5CYII=";
  string public constant DOGE_CROSSED =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEV0AFEVEQ7///9FdOUhAAAAAXRSTlMAQObYZgAAABhJREFUOMtjYBjEQAKNr8IwCkbBKBhEAADcNAA9lvR/RAAAAABJRU5ErkJggg==";
  string public constant DOGE_CLOSED =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAQMAAACQp+OdAAAABlBMVEUAAACfdzgbVBGtAAAAAXRSTlMAQObYZgAAABRJREFUKM9jYKA6YIMxEhhGwXAHAMNOAGfViymQAAAAAElFTkSuQmCC";
  string public constant DOGE_3D =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAADFBMVEVx+wP/AABBquz8/v/7RaQZAAAAAXRSTlMAQObYZgAAAB9JREFUOMtjYBi04D8QoIpcf42m5I89wygYBaNgwAAAHVsG+hdSEVQAAAAASUVORK5CYII=";
  string public constant DOGE_LASER =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEUAABz/QUH/cnKceMWeAAAAAXRSTlMAQObYZgAAAB1JREFUOMtjYBg8QAGdPwNNYIYCAR2jYBSMAnoCABoqAbGPkLppAAAAAElFTkSuQmCC";
  string public constant DOGE_SUN =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAQMAAACQp+OdAAAABlBMVEVya3UfGhWbBPmKAAAAAXRSTlMAQObYZgAAABdJREFUKM9jYKA24P//AcpKYxgFwx0AAJiZAmUBXFhvAAAAAElFTkSuQmCC";

  // Front view
  // Mouse: 0
  string public constant FRONT_MOUSE_RIGHT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgCAAAAAA+4qcQAAAAAnRSTlMAAHaTzTgAAAAYSURBVCjPY2AgEsyZA8Fw8FEFgkfBcAYA3bAEmxgUpywAAAAASUVORK5CYII=";
  string public constant FRONT_MOUSE_LEFT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgCAAAAAA+4qcQAAAAAnRSTlMAAHaTzTgAAAAYSURBVCjPY2AgEsyZA8FwoPIRgkfBcAYA3BYEm2WQB0sAAAAASUVORK5CYII=";
  string public constant FRONT_MOUSE_CROSSED =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgCAAAAAA+4qcQAAAAAnRSTlMAAHaTzTgAAAAdSURBVCjPY2AgEsyZA8FwoPKRgeGjCrHaR8HQBADc4wSbx3hv2QAAAABJRU5ErkJggg==";
  string public constant FRONT_MOUSE_3D =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAADFBMVEUAAADx8fFGw/z8RkZ76pEBAAAAAXRSTlMAQObYZgAAABdJREFUCNdjYAAD0VAgERUPYrEyDCYAALi7AT4MkX99AAAAAElFTkSuQmCC";
  string public constant FRONT_MOUSE_LASER =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAAD+hob5Pz8OwnIiAAAAAXRSTlMAQObYZgAAABVJREFUCNdjYEAAFhYgISkJYw0KAAAlXQBDsjfRKgAAAABJRU5ErkJggg==";
  string public constant FRONT_MOUSE_SUN =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgCAAAAAA+4qcQAAAAAnRSTlMAAHaTzTgAAAAeSURBVCjPY2AgBBgZGBgYVKCcOwhxFRUIHgXDGQAABmMBkrRf8jEAAAAASUVORK5CYII=";

  // Frog: 1
  string public constant FRONT_FROG_RIGHT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAADFBMVEUAAABCpkz///8AAADaoYegAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYAhgZWBg2MDNMDgBAKTJARGvt+qEAAAAAElFTkSuQmCC";
  string public constant FRONT_FROG_LEFT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAADFBMVEUAAABCpkwAAAD///8qussDAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYAhgZWBg2MDNMDgBAKTJARGvt+qEAAAAAElFTkSuQmCC";
  string public constant FRONT_FROG_CROSSED =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAADFBMVEUAAABCpkwAAAD///8qussDAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYAhgZWBg2MDHMDgBAKaRARSCVSMWAAAAAElFTkSuQmCC";
  string public constant FRONT_FROG_CLOSED =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAABCpkwujUVVHvfnAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYAhgZWBgWMDFMDgBAJqhAQBfDkj7AAAAAElFTkSuQmCC";
  string public constant FRONT_FROG_LASER =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAADfbmDfNB6638WMAAAAAXRSTlMAQObYZgAAABZJREFUCNdjYBBgYWBgSJEEEmDWIAMAYxwApt1kpUkAAAAASUVORK5CYII=";
  string public constant FRONT_FROG_SUN =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAQMAAAAhR2qPAAAABlBMVEUAAAAcEwDRtKJJAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYGBg4P/AwFfAQBsAAIZyAX7ot6HTAAAAAElFTkSuQmCC";

  // Cats: 2
  string public constant FRONT_CAT_RIGHT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAADW4cgICAgpWG32AAAAAXRSTlMAQObYZgAAABFJREFUCNdjYMAJJCQYBh4AABl4ADERYRJzAAAAAElFTkSuQmCC";
  string public constant FRONT_CAT_LEFT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAAAICAjW4cjBKskuAAAAAXRSTlMAQObYZgAAABFJREFUCNdjYMAJJCQYBh4AABl4ADERYRJzAAAAAElFTkSuQmCC";
  string public constant FRONT_CAT_CROSSED =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAADW4cgICAgpWG32AAAAAXRSTlMAQObYZgAAABFJREFUCNdjYMAJJFQYBh4AAB+oAD1GfLEsAAAAAElFTkSuQmCC";
  string public constant FRONT_CAT_CLOSED =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAQMAAAAhR2qPAAAABlBMVEUAAADzkhKiK+2WAAAAAXRSTlMAQObYZgAAABBJREFUCNdjYEAFbAkMVAUAH+AAZ1iIvc8AAAAASUVORK5CYII=";
  string public constant FRONT_CAT_3D =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAADFBMVEUAAAD///9gt+LiYGCclyvXAAAAAXRSTlMAQObYZgAAABhJREFUCNdjYMAGQkOBRGYtkAgRZRhQAAAHagH68ks+IQAAAABJRU5ErkJggg==";
  string public constant FRONT_CAT_LASER =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAAD4koPzUjrXizT8AAAAAXRSTlMAQObYZgAAABVJREFUCNdjYMAGBFiARIokjDWAAABWOACmNAJ9WgAAAABJRU5ErkJggg==";
  string public constant FRONT_CAT_SUN =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgCAAAAAA+4qcQAAAAAnRSTlMAAHaTzTgAAAAeSURBVCjPY2CgHDAyMDAwcEA5P+DCHBwQPAqGMAAAC6oBIm0YoIMAAAAASUVORK5CYII=";

  // Ape: 3
  string public constant FRONT_APE_RIGHT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAADFBMVEUAAACSayD///8AAABjE7LuAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYEAAkQAgobOBYTABALRUAUE6qUrJAAAAAElFTkSuQmCC";
  string public constant FRONT_APE_LEFT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAADFBMVEUAAACSayAAAAD///+TCP5NAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYEAAkQAgobOBYTABALRUAUE6qUrJAAAAAElFTkSuQmCC";
  string public constant FRONT_APE_CROSSED =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAADFBMVEUAAACSayAAAAD///+TCP5NAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYEAAkQAgofOAYTABAM70AXFIS3QeAAAAAElFTkSuQmCC";
  string public constant FRONT_APE_CLOSED =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAACSayCCXhvR8cEyAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYEAAkQAgobGAYTABAKk4AS2OnR7CAAAAAElFTkSuQmCC";
  string public constant FRONT_APE_3D =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAADFBMVEUAAAD//PffNB5PoNu2dNPXAAAAAXRSTlMAQObYZgAAABdJREFUCNdjYECA0FAgkfkFxAphGCQAAH9nArGt+abTAAAAAElFTkSuQmCC";
  string public constant FRONT_APE_LASER =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAADfb2HfNB9IBLvPAAAAAXRSTlMAQObYZgAAABVJREFUCNdjYEAAAQEgkZICYw0KAACTlAEJt/qpQQAAAABJRU5ErkJggg==";
  string public constant FRONT_APE_SUN =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAQMAAAAhR2qPAAAABlBMVEUAAAAoHAB1TvPKAAAAAXRSTlMAQObYZgAAABNJREFUCNdjYAAD/g8MbAcYaAAAmdsBxjfxqA8AAAAASUVORK5CYII=";

  // Alien: 4
  string public constant FRONT_ALIEN_RIGHT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAABnzugJDAfufAhvAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYEADEhJAQkWFYZAAAEIEAHmk+RO7AAAAAElFTkSuQmCC";
  string public constant FRONT_ALIEN_LEFT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAAAICAhsyOKWHuTVAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYEADEhJAQkWFYZAAAEIEAHmk+RO7AAAAAElFTkSuQmCC";
  string public constant FRONT_ALIEN_CROSSED =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAAAICAhsyOKWHuTVAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYEADEipAQkWCYZAAAEJAAHnqcWUsAAAAAElFTkSuQmCC";
  string public constant FRONT_ALIEN_CLOSED =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAABWwN5BuNpNaNzWAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYEADIiJAQkODYZAAAEHcAHnnfXiLAAAAAElFTkSuQmCC";
  string public constant FRONT_ALIEN_3D =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAADFBMVEUAAAD8/v/iR0xHx+LiC8udAAAAAXRSTlMAQObYZgAAABhJREFUCNdjYECA0FAgkVkLJEJEGQYJAAAbJAH6EljucAAAAABJRU5ErkJggg==";
  string public constant FRONT_ALIEN_LASER =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAADmgYzeVmU+WfbBAAAAAXRSTlMAQObYZgAAABtJREFUCNdjYEAAFhYgISkJJFJSgISAAMPAAwCdDQEjJ/SyKQAAAABJRU5ErkJggg==";
  string public constant FRONT_ALIEN_SUN =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgCAAAAAA+4qcQAAAAAnRSTlMAAHaTzTgAAAAeSURBVCjPY2AgGTAyMDAwcEA5P+DCHBwQPAqGEwAAHtsBIq1KNLoAAAAASUVORK5CYII=";

  // Doge: 5
  string public constant FRONT_DOGE_RIGHT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAAD///8VEQ7dSuz9AAAAAXRSTlMAQObYZgAAABBJREFUCNdjYIAACSgebAAAHMAAMYYQwVYAAAAASUVORK5CYII=";
  string public constant FRONT_DOGE_LEFT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAAAVEQ7///9tmZX7AAAAAXRSTlMAQObYZgAAABBJREFUCNdjYIAACSgebAAAHMAAMYYQwVYAAAAASUVORK5CYII=";
  string public constant FRONT_DOGE_CROSSED =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAAAVEQ7///9tmZX7AAAAAXRSTlMAQObYZgAAABJJREFUCNdjYIAACSBWYRh8AAAjsAA9lDVa0QAAAABJRU5ErkJggg==";
  string public constant FRONT_DOGE_CLOSED =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAQMAAAAhR2qPAAAABlBMVEUAAACfdzgbVBGtAAAAAXRSTlMAQObYZgAAABFJREFUCNdjYACCBAY2BhoBACSWAGeG8raLAAAAAElFTkSuQmCC";
  string public constant FRONT_DOGE_3D =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAADFBMVEUAAAD8/v//AABBquxVNP1bAAAAAXRSTlMAQObYZgAAABhJREFUCNdjYACD0FAgkVkLJEJEGQYTAAAlAQH6aSoA1gAAAABJRU5ErkJggg==";
  string public constant FRONT_DOGE_LASER =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAAD/cnL/QUFzoqIbAAAAAXRSTlMAQObYZgAAABdJREFUCNdjYGAQYADiFCCRAmYxDCoAAJtQAQnk4ZJQAAAAAElFTkSuQmCC";
  string public constant FRONT_DOGE_SUN =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAQMAAAAhR2qPAAAABlBMVEUAAAAfGhVv7UOyAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYGBg4P/AwJbAQBsAAH4qAWZN2x1aAAAAAElFTkSuQmCC";

  constructor() {
    _tiers = [3100, 6100, 8100, 9300, 9800, 9900, 10000];
  }

  function getName(uint256 traitIndex)
    public
    pure
    override
    returns (string memory name)
  {
    if (traitIndex == 0) {
      return "Right";
    } else if (traitIndex == 1) {
      return "Left";
    } else if (traitIndex == 2) {
      return "Crossed";
    } else if (traitIndex == 3) {
      return "Sun"; 
    } else if (traitIndex == 4) {
      return "Closed";
    } else if (traitIndex == 5) {
      return "3D";
    } else if (traitIndex == 6) {
      return "Laser";
    }
  }

  function _getLayer(
    uint256 traitIndex,
    uint256 layerIndex,
    string memory prefix
  ) internal view override returns (string memory layer) {
    if (traitIndex == 0) {
      return _indexedLayer(layerIndex, prefix, "RIGHT");
    } else if (traitIndex == 1) {
      return _indexedLayer(layerIndex, prefix, "LEFT");
    } else if (traitIndex == 2) {
      return _indexedLayer(layerIndex, prefix, "CROSSED");
    } else if (traitIndex == 3) {
      return _indexedLayer(layerIndex, prefix, "SUN");
    } else if (traitIndex == 4) {
      return _indexedLayer(layerIndex, prefix, "CLOSED");
    } else if (traitIndex == 5) {
      return _indexedLayer(layerIndex, prefix, "3D");
    } else if (traitIndex == 6) {
      return _indexedLayer(layerIndex, prefix, "LASER");
    }
  }

  function _getLayerPrefix(uint256 layerIndex)
    internal
    pure
    override
    returns (string memory prefix)
  {
    if (layerIndex == 0) {
      return "FROG_";
    } else if (layerIndex == 1) {
      return "MOUSE_";
    } else if (layerIndex == 2) {
      return "APE_";
    } else if (layerIndex == 3) {
      return "CAT_";
    } else if (layerIndex == 4) {
      return "ALIEN_";
    } else if (layerIndex == 5) {
      return "DOGE_";
    }
  }
}

