//SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "./Trait.sol";

contract Hats is Trait {
  // Skin view
  string public constant SPECIAL_OPS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAD1BMVEVldC1BQDp+dliPhGKbkW5wpPPzAAAAAXRSTlMAQObYZgAAALJJREFUSMftkF0OhCAMhIvsATTxALvUA5C2B3Bb73+mrRqjxMjDPvOFv4EBBgCcZSsnL5b3VcPsc1fNIgQ11GipGkxRqgbGpPUTjKyYyB5ycA5Nkrjc4bmuOn7GfN4HIOgGj83+thQTz/E75k6855TX46P/Spf3GskMZSLhpGtrt4CJSMyLCqOi3l9jAbaACD1NRHwz5HCM+shouA52HYoOzoXhMAxP/xYKf6PRaDQa//ADr8MV+48oCrMAAAAASUVORK5CYII=";
  string public constant CROWN =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAFVBMVEUAAAACZ7cxtwI16QL/0Sn/3Vv/5430D+K1AAAAAXRSTlMAQObYZgAAAERJREFUSMdjYMACEgJY2RgoAgEMDKwMtAWUW4HXmwkhrmyJQaZiIBqEMRS4uqWEuDqrhIBpIGYYBaNgFIyCUTAKRgwAAEUsCuU59t5pAAAAAElFTkSuQmCC";
  string public constant MOTORCYCLE =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAHlBMVEUAAAAkJCQ6OjpUVFRhYWH/PT1ubm7/V1ejo6PX19epJvNBAAAAAXRSTlMAQObYZgAAAM5JREFUSMftkDEOwjAMRcPCTHoCagSsCLfKihTT7FCJvUKBmbT0BpyB4+KSFBbICfImy3n6yY8QPyjUsUBG/EOrlqJCUTri0/8CDgkxQZu6igpkWhsX9ncbfSSZiICFJjS1tfZMqNxbkjJbPWCsqJEP2spaIv4wzauJlHB9NvOQgM4PFxoTpE/Ig3Da+GHa6a8goQHp973bBcF0WH6EDPIg3GDhhwbWvXK9fwNHyJnfA9fjS6ZcApZ9dxAiZHxqDqh2KIFbGOMSiUQikYjzAm+BMKFIftxBAAAAAElFTkSuQmCC";
  string public constant KNIT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABAAgMAAADXB5lNAAAACVBMVEUwAIGvRA7fVhK/WBtCAAAAAXRSTlMAQObYZgAAACtJREFUOMtjYGBYtYoBFcAEtFbQQwDOhQAGdBAKBXCBmVDAMApGwSgYWAAARq4cTV6NFBEAAAAASUVORK5CYII=";
  string public constant HARDHAT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAD1BMVEVldC3gvADDw8P/2hD//JQq30h5AAAAAXRSTlMAQObYZgAAAFBJREFUSMdjYAACYyBgwAcMDYWFUQQMmIegAmNlI1RvMikgSYIAUAEMgAVZHJAUgNQgYQZBQQZGFScBEA3G6EAQDTCMglEwCkbBKBgFwwUAANLMDPQRsBm8AAAAAElFTkSuQmCC";
  string public constant KNIGHT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAG1BMVEX4ClzkOzvuZGSZmZmzs7PAwMDNzc3a2trn5+eNpld+AAAAAXRSTlMAQObYZgAAALxJREFUSMftkTEOwjAMRSNRlZ2he4fCipQcoFLtnUp2ZlqRdGVKegN6bFIY0wYOkDdaT/a3LcQGyH0lAUDswTie04Kup6sQxa6AuvZJge0p3YGHy48OfTWr9qASIadFtsX2FsxMqP2y+MmODXMsEEAQ5pd3emg0RgIAkSifwltnDSNFAtH3gt5bzQ+OcyCoT9E5Y0yYFwkddID30jtjQ1yKR6jwpCBYGxIYhC4S5MrtCLxCIEUmk8lkMn/wBpnuNHgsWh6yAAAAAElFTkSuQmCC";
  string public constant RAINBOW =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAD1BMVEVldC3lUEdPjONl5Enj5Ekn+BeYAAAAAXRSTlMAQObYZgAAAG5JREFUSMftz7ENwzAMRFEi8QA5aYGA0AAOqAmM23+mUJ2vcDKA+RuCwGNBs2wQsF850c/7g3gpGAgBA7sC7wq8K4jpft6f098K2BSwKZiEgI1QQKJdv+gxF8j5AXjYvxJGHmDNPKBVVVVV1W36AkLsDMOwXhdMAAAAAElFTkSuQmCC";
  string public constant GAS =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAFVBMVEVodAAQEBAqKipeXl5sbGyGhobN4uAxiuNyAAAAAXRSTlMAQObYZgAAAGZJREFUSMdjYBhZgJFRQACZb+DAwgznsAawBqCoNjZG1R0awBqKzFcCAhQFYQlsqch8BSYFJtIUMAkwKqDwFYUU8ClgcQBBFC8KMCJ7kdnQUUTYAEWBoCB+BaNgFIyCUTAKRgEBAAAFzwlvyOPfIwAAAABJRU5ErkJggg==";
  string public constant HAMBURGER =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAGFBMVEUAAABWMBLzPSHEaB3miT488yF9+2z/6B+OeA4iAAAAAXRSTlMAQObYZgAAAI5JREFUSMftkTEOwyAMRb3Q3RN7z+AbmAN4gbmL2TPl+nVoIkUQoiqz32AJva9vEAAGpx8wY5N0HyBOzPPAHyvoPkD7JeYNtGl+uGJ3qbXQRYs1s6njITwENFfVrKWUrNUOQcNLigapIgEE4N1R4dNMk8XG2jGsiLgiLhEXmxgRhwB2XP7kGXAcx3GcB3wBQf41+gnJ8/EAAAAASUVORK5CYII=";
  string public constant ASTRONAUT =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAJFBMVEUAAABwcHAOmNwQpe0Tsf8uuv9Uzf/Nzc236//n5+fx8fH09PT96emkAAAAAXRSTlMAQObYZgAAAPFJREFUSMftkTtuwzAMQIkuRrp18p4cITlAB/cI9hGCjvJkqFk6ZsxmSF6yklq6BSIvF8m1ChuFfQK9hYTwQPEDkChalVLP3pheaVgwE5gQ/wszCC0aALMqsHN2W/DMmwIS0XYFETKBVUEGkYXQBVJunAze+EGY2ZKT+PZyqJrr998E4m8AOyuhD+JR2B9Ozed1EtzD/8T46rRFdMMk1OdzEtqv2yg8yrDOqcL+9NEkwbaX+ySEdVr7Kxyruo7n6BTY8jJVaLHvNI5Nhj+q9yi8KUBECVfbkbDpQdNizKJUEOc3nR5DX+j1ZWUymUwmM+MJxypxehjjjQAAAAAASUVORK5CYII=";
  string public constant USHANKA =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAElBMVEUAAAB5HByFhYWSkpKfn5+srKyqZcbPAAAAAXRSTlMAQObYZgAAAItJREFUSMftjzEKwzAMRQWtL9ATtLK6F8negxzvIXXuf5WaDK2DwZkLeugPH33EF0Bl2+eHk7C0Hqpzrd8iC4woSvMwEJB1GFBNcnIhpGHJgj4fAt2bVJbDspXLOl0ZX478/RLnaT/fSkmIHzdi5azKa/+Bx5SqJCGuiL4L8Lfe+ynFRzAMwzCMP+EDYuAXa3pgoK4AAAAASUVORK5CYII=";
  string public constant SANTA =
    "iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAAElBMVEVjb2zGJCrZKzHdQUbo6N/z8+6qFXUgAAAAAXRSTlMAQObYZgAAAH1JREFUSMftzrENw0AIhWGKZIDjlAGABeJHBkgK+kQ677+K3aWwwzUp+SokfiGITiwGoYyYzwLlNGBMA/Q0UEDTwHb5BVX8XLrs26bs5togfgjAwreIz9K6icnxkjzGGESxxou5nzwb8Z1CNNJnCfd8T5f3JLg+qZRSSvmLDRNvDyRpMVYXAAAAAElFTkSuQmCC";

  // Front view
  string public constant FRONT_SPECIAL_OPS =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAADFBMVEUAAAB+dliPhGKbkW5+ND/UAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYEjgZWBgcGBkGJwAAGqxAK/ONtuCAAAAAElFTkSuQmCC";
  string public constant FRONT_CROWN =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAQAAAAAz8sVhAAAAAnRSTlMAAHaTzTgAAAAMSURBVAjXY2CgLQAAAGAAATeQF3gAAAAASUVORK5CYII=";
  string public constant FRONT_MOTORCYCLE =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgCAAAAAA+4qcQAAAAAnRSTlMAAHaTzTgAAABMSURBVCjP7cyrDYAwAEDB4+NwiE7ACO2irNVuQYKoxyMIoWECBE+eeLzqYCGIKa8YLw9iijxQQyHDADPHtCsb+ntWFVpQtY9G/j7ZCRxkDJDlVoYwAAAAAElFTkSuQmCC";
  string public constant FRONT_KNIT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAQMAAAAhR2qPAAAABlBMVEUAAADfVhI86kBYAAAAAXRSTlMAQObYZgAAAA5JREFUCNdj4P/AQEsAAF4RAQAJJ6MzAAAAAElFTkSuQmCC";
  string public constant FRONT_HARDHAT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAAD/2hDDw8OFqE31AAAAAXRSTlMAQObYZgAAABRJREFUCNdjYIhMZWBgCGBlGJwAAKhHARREPXISAAAAAElFTkSuQmCC";
  string public constant FRONT_KNIGHT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAQAAAAAz8sVhAAAAAnRSTlMAAHaTzTgAAAAMSURBVAjXY2CgLQAAAGAAATeQF3gAAAAASUVORK5CYII=";
  string public constant FRONT_RAINBOW =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAADFBMVEUAAADj5EnlUEdPjONN8RqPAAAAAXRSTlMAQObYZgAAAA9JREFUCNdjYAhdzTCIAQCd9QEBc0kIcgAAAABJRU5ErkJggg==";
  string public constant FRONT_GAS =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgBAMAAADpp+X/AAAAD1BMVEUAAACGhobN4uAqKioQEBCW/DTpAAAAAXRSTlMAQObYZgAAAC5JREFUGNNjYGBgFGAUYAABQQFGQTBDSIFJEZXB7MBigMpgcWBxgDBcXCCMYQkAFYoDQpDT6ogAAAAASUVORK5CYII=";
  string public constant FRONT_HAMBURGER =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgBAMAAADpp+X/AAAAGFBMVEUAAADmiT7EaB19+2w88yHzPSH/6B9WMBInv3+2AAAAAXRSTlMAQObYZgAAADFJREFUGNNjYGAQBAIGEBBUFBQCM0xcTJzBjFAgADPSgADMKE8vK4cwgACiC6Z9WAIAD+MIYM1v0dEAAAAASUVORK5CYII=";
  string public constant FRONT_ASTRONAUT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgBAMAAADpp+X/AAAAGFBMVEUAAADNzc0OmNwQpe0Tsf8uuv9Uzf+36/+lKt1+AAAAAXRSTlMAQObYZgAAADFJREFUGNNjYGAQBAIGEFB2CSuHMEzC0qGM0DQwQ8nENQzCMHYJhTCUTVzADLj2YQkAcDMGf78bGZYAAAAASUVORK5CYII=";
  string public constant FRONT_USHANKA =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgCAAAAAA+4qcQAAAAAnRSTlMAAHaTzTgAAAAcSURBVCjPY2BgYGBYswZBMjAwMDCsQaFGwcgFAFp8BAmdVdSNAAAAAElFTkSuQmCC";
  string public constant FRONT_SANTA =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAQAAAAAz8sVhAAAAAnRSTlMAAHaTzTgAAAAMSURBVAjXY2CgLQAAAGAAATeQF3gAAAAASUVORK5CYII=";

  // Front armor view
  string public constant FRONT_ARMOR_SPECIAL_OPS =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgBAMAAADpp+X/AAAAD1BMVEUAAACPhGKbkW5BQDp+dlh+zwHRAAAAAXRSTlMAQObYZgAAAB9JREFUGNNjYGBgVDYSYAABIScRITBDUURIkWEUgAAAYMsBScRVzMEAAAAASUVORK5CYII=";
  string public constant FRONT_ARMOR_CROWN =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgBAMAAADpp+X/AAAAFVBMVEUAAAD/540CZ7f/3VsxtwI16QL/0SnadNOZAAAAAXRSTlMAQObYZgAAABlJREFUGNNjYGAQMglWZACB5FQ3M4ZRgAIAKtAB/5DJXMEAAAAASUVORK5CYII=";
  string public constant FRONT_ARMOR_MOTORCYCLE =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgBAMAAADpp+X/AAAAElBMVEUAAABUVFRhYWH/V1f/PT1ubm5TBb01AAAAAXRSTlMAQObYZgAAACRJREFUGNNjYGAQVHYKZQABQWEjVQZigQADAytMVyjRuoYcAAALBQIHLifLJQAAAABJRU5ErkJggg==";
  string public constant FRONT_ARMOR_KNIT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAACvRA7fVhK/CDrWAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYACD0FAgMXMmw6ADABZDAd3yppsFAAAAAElFTkSuQmCC";
  string public constant FRONT_ARMOR_HARDHAT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAADFBMVEUAAAD//JTgvADDw8N9xan+AAAAAXRSTlMAQObYZgAAABhJREFUCNdjYGB0YGBg0K0AEqtWMQw6AABOmAI7b+TcDwAAAABJRU5ErkJggg==";
  string public constant FRONT_ARMOR_KNIGHT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgCAAAAAA+4qcQAAAAAnRSTlMAAHaTzTgAAABESURBVCjP7cyxDUBAAAXQd3LtH8ACDGB0cxiAASxgAYVERHWVyhvgFZgjET06t8PTsmlVrjSTJQbUd1phN5K1uf197wSkaQiNqd5CiwAAAABJRU5ErkJggg==";
  string public constant FRONT_ARMOR_RAINBOW =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAADj5EnlUEfV0W1oAAAAAXRSTlMAQObYZgAAABFJREFUCNdjYACD0FUMgxMAAJhdAQAOYUYrAAAAAElFTkSuQmCC";
  string public constant FRONT_ARMOR_GAS =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgCAAAAAA+4qcQAAAAAnRSTlMAAHaTzTgAAABOSURBVCjP7cxBCYBAFIThb8UAno3wMokJXirZTEYwwCbw4IIgBvDgfxn4mZkCrNhAgbisvacgovvBg9Irh/leSDJJGKFNS5W1vX78fJMT4r8KaMLOpcEAAAAASUVORK5CYII=";
  string public constant FRONT_ARMOR_HAMBURGER =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgAgMAAABm5xBfAAAACVBMVEUAAAA88yF9+2wIpCLGAAAAAXRSTlMAQObYZgAAABRJREFUCNdjYEAAt4lAwpGFYTABAKLiAR0JrN+2AAAAAElFTkSuQmCC";
  string public constant FRONT_ARMOR_ASTRONAUT =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgCAAAAAA+4qcQAAAAAnRSTlMAAHaTzTgAAAAxSURBVCjPY2RgYGD48pmBgfczAy8PAxQ8R6GoBM4iGcoIYT1jYJBiYJCkqjWjgJoAAB/QCIUq0ToRAAAAAElFTkSuQmCC";
  string public constant FRONT_ARMOR_USHANKA =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgBAMAAADpp+X/AAAAD1BMVEUAAACfn5+SkpKFhYV5HByeMTx6AAAAAXRSTlMAQObYZgAAAB9JREFUGNNjYGBgVDZWYAABZRNnQzBDyMhYiGEUgAAA7GUBzApMvPIAAAAASUVORK5CYII=";
  string public constant FRONT_ARMOR_SANTA =
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAgBAMAAADpp+X/AAAAElBMVEUAAADdQUbZKzHGJCrz8+7o6N+uWPkKAAAAAXRSTlMAQObYZgAAAB9JREFUGNNjYGAQMlYyYgABk5AQZzDDlYEhhGEUgAAAfMQCUmAKvrwAAAAASUVORK5CYII=";

  constructor() {
    _frontArmorTraitsExists = true;
    _tiers = [
      4350,
      5150,
      5950,
      6600,
      7300,
      7900,
      8500,
      9000,
      9300,
      9500,
      9700,
      9900,
      10000
    ];
  }

  function getName(uint256 traitIndex)
    public
    pure
    override
    returns (string memory name)
  {
    if (traitIndex == 0) {
      return "";
    } else if (traitIndex == 1) {
      return "Knitted Cap";
    } else if (traitIndex == 2) {
      return "Hard Hat";
    } else if (traitIndex == 3) {
      return "Special Ops";
    } else if (traitIndex == 4) {
      return "Santa";
    } else if (traitIndex == 5) {
      return "Ushanka";
    } else if (traitIndex == 6) {
      return "Gas Mask";
    } else if (traitIndex == 7) {
      return "Rainbow Beanie";
    } else if (traitIndex == 8) {
      return "Motorcycle Helmet";
    } else if (traitIndex == 9) {
      return "Hamburger";
    } else if (traitIndex == 10) {
      return "Astronaut";
    } else if (traitIndex == 11) {
      return "Knight";
    } else if (traitIndex == 12) {
      return "Crown";
    }
  }

  function _getLayer(
    uint256 traitIndex,
    uint256,
    string memory prefix
  ) internal view override returns (string memory layer) {
    if (traitIndex == 0) {
      return "";
    } else if (traitIndex == 1) {
      return _layer(prefix, "KNIT");
    } else if (traitIndex == 2) {
      return _layer(prefix, "HARDHAT");
    } else if (traitIndex == 3) {
      return _layer(prefix, "SPECIAL_OPS");
    } else if (traitIndex == 4) {
      return _layer(prefix, "SANTA");
    } else if (traitIndex == 5) {
      return _layer(prefix, "USHANKA");
    } else if (traitIndex == 6) {
      return _layer(prefix, "GAS");
    } else if (traitIndex == 7) {
      return _layer(prefix, "RAINBOW");
    } else if (traitIndex == 8) {
      return _layer(prefix, "MOTORCYCLE");
    } else if (traitIndex == 9) {
      return _layer(prefix, "HAMBURGER");
    } else if (traitIndex == 10) {
      return _layer(prefix, "ASTRONAUT");
    } else if (traitIndex == 11) {
      return _layer(prefix, "KNIGHT");
    } else if (traitIndex == 12) {
      return _layer(prefix, "CROWN");
    }
  }
}

