// THIS FILE IS AUTOGENERATED DURING MIGRATION, DO NOT EDIT BY HAND
pragma solidity 0.5.12;

import { Dai } from "./dai.sol";
import { DaiJoin } from "./join.sol";
import { Pot } from "./pot.sol";
import { Vat } from "./vat.sol";

contract RuntimeConstants {
	Dai constant public dai = Dai(0x6B175474E89094C44Da98b954EedeAC495271d0F);
	Vat constant public vat = Vat(0x35D1b3F3D7966A1DFe207aa4514C12a259A0492B);
	Pot constant public pot = Pot(0x197E90f9FAD81970bA7976f33CbD77088E5D7cf7);
	DaiJoin constant public daiJoin = DaiJoin(0x9759A6Ac90977b93B58547b4A71c78317f391A28);
	address constant public uniswapExchange = 0x918Af0FB5517aC5b8B34240203408CeDBBa09Bd9;
}

