// SPDX-License-Identifier: MIT
pragma solidity >=0.6.12;
interface IGetBackETHHelperV2 {
  function BASE (  ) external view returns ( uint256 );
  function FEE (  ) external view returns ( uint256 );
  function FeeDiscountRatio (  ) external view returns ( uint256 );
  function FeeDiscountToken (  ) external view returns ( address );
  function FeeTokenBalanceNeeded (  ) external view returns ( uint256 );
  function IsEligibleForFeeDiscount ( address user ) external view returns ( bool );
  function QueueDelay (  ) external view returns ( uint256 );
  function UniRouter (  ) external view returns ( address );
  function Unifactory (  ) external view returns ( address );
  function WETH (  ) external view returns ( address );
  function addWhitelisted ( address addx ) external;
  function addr (  ) external view returns ( address );
  function addrSwapStats ( address ) external view returns ( uint256 );
  function checkPerm ( address sender, uint256 timex, address token ) external view returns ( bool );
  function clearQueueFromOwner (  ) external;
  function feeGetter (  ) external view returns ( address );
  function getSendAfterFee ( uint256 amount, address user, uint256 fee ) external view returns ( uint256 amt );
  function getTimeLeftToTimeout (  ) external view returns ( uint256 );
  function getTokens (  ) external view returns ( address[] memory);
  function getUsers (  ) external view returns ( address[] memory);
  function getWETHBalance (  ) external view returns ( uint256 );
  function isAwaitingSwap (  ) external view returns ( bool );
  function isQueueEmpty (  ) external view returns ( bool );
  function owner (  ) external view returns ( address );
  function queue ( address tokentoQueue ) external;
  function recoverTokens ( address token ) external;
  function renounceOwnership (  ) external;
  function revokeWhitelisted ( address addx ) external;
  function setFeeDiscountRatio ( uint256 ratio ) external;
  function setFeeDiscountToken ( address token ) external;
  function setFeeGetter ( address newFeeGetter ) external;
  function setQueueDelay ( uint256 newDelay ) external;
  function setServicefee ( uint256 fee ) external;
  function setTokensForFeeDiscount ( uint256 tokenAmt ) external;
  function shouldClearQueue (  ) external view returns ( bool );
  function swapQueuedToken (  ) external returns ( uint256[] memory amounts );
  function swapToETH ( address tokenx ) external returns ( uint256[] memory  amounts );
  function time (  ) external view returns ( uint256 );
  function tokenHasBurn ( address ) external view returns ( bool );
  function tokenQueued (  ) external view returns ( address );
  function tokenSwappedSuccess ( address ) external view returns ( bool );
  function tokenTried ( address ) external view returns ( bool );
  function totalETHFees (  ) external view returns ( uint256 );
  function totalETHSwapped (  ) external view returns ( uint256 );
  function totalTries (  ) external view returns ( uint256 );
  function transferOwnership ( address newOwner ) external;
  function whitelistedExecutors ( address ) external view returns ( bool );
}

